spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}?sslmode=require&tcpKeepAlive=true&connectTimeout=60&socketTimeout=60
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

api.gnews.key=${GNEWS_API_KEY}
youtube.api.key=AIzaSyDcNcgvmYx9hzY4h7isZ0or2s6cJeerd70
youtube.playlist.id=PLhnExfBbbmAQrPacK4YEdVQbwBjyrXNzL

spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=900000
spring.datasource.hikari.maximum-pool-size=3

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect