GET http://localhost:8080/denuncias
### Criar uma Nova Postagem na Comunidade
POST http://localhost:9000/api/postagens
Content-Type: application/json

{
  "conteudo": "Este é um post de teste automatizado para verificar o funcionamento do novo fórum do CyberGuard!",
  "autorId": 1
}

### Listar todas as postagens da Comunidade
GET http://localhost:9000/api/postagens